[execution-client]
ethereum-json-rpc-endpoint = "http://localhost:8545"
engine-api-json-rpc-endpoint = "http://localhost:8552"

[p2p-config]
port = 3322

[validator]
validator-key = "0x1dd171cec7e2995408b5513004e8207fe88d6820aeff0d82463b3e41df251aae"
