[persistence]
data-path="/tmp/maru-db"

[qbft-options]
validator-set = ["0x1b9abeec3215d8ade8a33607f2cf0f4f60e5f0d0"]

[qbft-options.validator-duties]
communication-margin=100m

[p2p-config]
port = 3322
ip-address = "127.0.0.1"

[payload-validator]
engine-api-endpoint = { endpoint = "http://localhost:8550" }
eth-api-endpoint = { endpoint = "http://localhost:8545" }

[follower-engine-apis]
"follower-besu" = { endpoint = "http://localhost:9550" }
"follower-erigon" = { endpoint = "http://localhost:11551", jwt-secret-path = "../docker/jwt" }
"follower-nethermind" = { endpoint = "http://localhost:10550", jwt-secret-path = "../docker/jwt" }
"follower-geth" = { endpoint = "http://localhost:8561", jwt-secret-path = "../docker/jwt" }
