[execution-client]
ethereum-json-rpc-endpoint = "http://localhost:8545"
engine-api-json-rpc-endpoint = "http://localhost:8550"
min-time-between-get-payload-attempts=6000m

[qbft-options]
communication-margin=100m
data-path="/tmp/maru-db"

[p2p-config]
port = 3322

[validator]
validator-key = "0xdead"
