[execution-client]
ethereum-json-rpc-endpoint = "http://sequencer:8545"
engine-api-json-rpc-endpoint = "http://follower-geth:8555"
[sot-endpoint]
endpoint = "http://sequencer:8545"

[qbft-options]
communication-margin=100m
data-path="/tmp/maru-db"

[p2p-config]
port = 3322

[validator]
private-key = "0xdead"
jwt-secret-path = "/secret/path"
min-time-between-get-payload-attempts=800m
el-client-endpoint = "http://sequencer:8545"
